title: "Research Project Website"
email: ""
url: "https://johnletey.github.io/A-Study-of-Transcription-and-Its-Affects/"
docs_github: "https://github.com/JohnLetey/A-Study-of-Transcription-and-Its-Affects/"
exclude: [src, .travis.yml, README.md, package.json, requirements.txt, run.sh, run_server.py]
markdown: kramdown
permalink: :/title/
syntax-highlighting:
  enabled: true
kramdown:
  hard_wrap: false
  input: GFM
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
css:
  css_dir: assets/css
js:
  js_dir: assets/js
# sass:
#   sass_dir: assets/stylesheets
