# Site settings
title: A Study of Transcription and Its Affects
email: john.letey@colorado.edu
description: The website for a research project worked on by John Letey and David Knox that studied transcription and its affects.

baseurl: "/A-Study-of-Transcription-and-Its-Affects"
url: https://johnletey.github.io/A-Study-of-Transcription-and-Its-Affects
git_address: https://github.com/johnletey/A-Study-of-Transcription-and-Its-Affects
git_edit_address: https://github.com/johnletey/A-Study-of-Transcription-and-Its-Affects/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
